let RevString = "&rev=6";
// Rev strings known to server, probably:
// rev=3 is the minimum allowed by server, probably pq6.1
// rev=4 is pq6.2 the longstanding delphi client
// rev=5 is pq6.3 presumably the lazarus port or other unofficial release
// rev=6 is this here, pq-web multiplayer enabled

var K = {};

K.Traits = ["Name", "Race", "Class", "Level"];

K.PrimeStats = ["STR", "CON", "DEX", "INT", "WIS", "CHA"];
K.Stats = K.PrimeStats.slice(0).concat(["HP Max", "TP Max"]);

K.Equips = [
  "Weapon",
  "Accessory",
  "Headwear",
  "Eyewear",
  "Body Armor",
  "Jacket",
  "Gloves",
  "Wristwear",
  "Belt",
  "Legwear",
  "Footwear",
];

K.Spells = [
  "Basic Cooking",
  "Time Management",
  "Public Speaking",
  "First Aid",
  "Personal Finance",
  "Social Media",
  "Computer Basics",
  "Foreign Language",
  "Project Management",
  "Data Analysis",
  "Digital Marketing",
  "Programming",
  "Cybersecurity",
  "AI Interaction",
  "Virtual Reality",
  "Drone Operation",
  "Cryptocurrency Trading",
  "Neural Interface",
  "Quantum Computing",
  "Reality Hacking",
  "Consciousness Transfer",
  "Biometric Manipulation",
  "Temporal Navigation",
  "Memory Implantation",
  "Synthetic Telepathy",
  "Digital Immortality",
  "Neural Network Integration",
  "Quantum Entanglement Control",
  "Reality Matrix Access",
  "Omniscient Data Mining",
];

K.OffenseAttrib = [
  "Polished|+1",
  "Serrated|+1",
  "Heavy|+1",
  "Pronged|+2",
  "Steely|+2",
  "Vicious|+3",
  "Venomed|+4",
  "Stabbity|+4",
  "Dancing|+5",
  "Invisible|+6",
  "Vorpal|+7",
];

K.DefenseAttrib = [
  "Studded|+1",
  "Banded|+2",
  "Gilded|+2",
  "Festooned|+3",
  "Holy|+4",
  "Cambric|+1",
  "Fine|+4",
  "Impressive|+5",
  "Custom|+3",
];

K.Accessories = [
  "Paper Clip|0",
  "Rubber Band|0",
  "Safety Pin|0",
  "Button|0",
  "String|0",
  "Twist Tie|0",
  "Bread Clip|0",
  "Bottle Cap|0",
  "Coin|0",
  "Ticket Stub|0",
  "Dog Tags|1",
  "Key Ring|1",
  "Wallet|1",
  "Cigarette Lighter|1",
  "Matches|1",
  "Compass|1",
  "Whistle|1",
  "Medal|1",
  "Badge|1",
  "Business Card|1",
  "Calculator|2",
  "Flashlight|2",
  "Swiss Army Knife|2",
  "Multi-tool|2",
  "Pepper Spray|2",
  "Personal Alarm|2",
  "Pager|2",
  "Transistor Radio|2",
  "Magnifying Glass|2",
  "Pocket Mirror|2",
  "Cell Phone|3",
  "GPS Device|3",
  "Digital Camera|3",
  "MP3 Player|3",
  "USB Drive|3",
  "RFID Card|3",
  "Electronic Key|3",
  "Two-Way Radio|3",
  "Bluetooth Speaker|3",
  "Portable Charger|3",
  "Smartphone|4",
  "Tablet|4",
  "Portable Charger|4",
  "Action Camera|4",
  "Drone Controller|4",
  "Security Token|4",
  "Credit Card Scanner|4",
  "Digital Wallet|4",
  "Power Bank|4",
  "Solar Panel|4",
  "Biometric Scanner|5",
  "Encryption Device|5",
  "Signal Jammer|5",
  "Bug Detector|5",
  "Frequency Scanner|5",
  "Digital Disguise|5",
  "Voice Changer|5",
  "ID Scrambler|5",
  "Data Recorder|5",
  "Mini Drone|5",
  "Military Radio|6",
  "Tactical GPS|6",
  "Body Camera|6",
  "Covert Mic|6",
  "Surveillance Kit|6",
  "Counter-Intel Device|6",
  "Digital Lock Pick|6",
  "Signal Interceptor|6",
  "Portable Jammer|6",
  "Field Computer|6",
  "Satellite Phone|7",
  "Quantum Encryption|7",
  "Advanced Scanner|7",
  "Stealth Device|7",
  "Identity Scrambler|7",
  "Digital Ghost|7",
  "Hack Tool|7",
  "Cyber Defense|7",
  "AI Assistant|7",
  "Neural Probe|7",
  "Brain Interface|8",
  "Memory Chip|8",
  "Skill Implant|8",
  "Cognitive Amplifier|8",
  "Neural Link|8",
  "Mind Bridge|8",
  "Thought Recorder|8",
  "Data Jack|8",
  "Reflex Booster|8",
  "Sensory Enhancer|8",
  "Bio Scanner|9",
  "Reality Filter|9",
  "Time Dilator|9",
  "Quantum Communicator|9",
  "Dimensional Scanner|9",
  "Energy Converter|9",
  "Matter Analyzer|9",
  "Field Generator|9",
  "Nano Swarm|9",
  "Phase Shifter|9",
  "Neural Network|10",
  "Consciousness Backup|10",
  "Mind Upload|10",
  "Digital Soul|10",
  "Synthetic Telepathy|10",
  "Hive Mind Access|10",
  "Collective Interface|10",
  "Thought Multiplexer|10",
  "Memory Palace|10",
  "Dream Weaver|10",
  "Reality Manipulator|11",
  "Quantum Entangler|11",
  "Space-Time Anchor|11",
  "Dimensional Key|11",
  "Universe Browser|11",
  "Timeline Editor|11",
  "Causality Loop|11",
  "Paradox Resolver|11",
  "Multiverse Gate|11",
  "Infinity Calculator|11",
  "God Mode Toggle|12",
  "Universal Remote|12",
  "Omniscience Module|12",
  "All-Seeing Eye|12",
  "Perfect Knowledge|12",
  "Complete Understanding|12",
  "Total Awareness|12",
  "Infinite Wisdom|12",
  "Ultimate Truth|12",
  "Final Answer|12",
  "Creation Engine|13",
  "Genesis Protocol|13",
  "Big Bang Button|13",
  "Universe Maker|13",
  "Reality Compiler|13",
  "Existence Parser|13",
  "Being Generator|13",
  "Life Spawner|13",
  "Soul Forger|13",
  "Consciousness Creator|13",
  "Transcendence Key|14",
  "Ascension Drive|14",
  "Enlightenment Core|14",
  "Omega Point|14",
  "Alpha Source|14",
  "Prime Mover|14",
  "First Cause|14",
  "Beginning End|14",
  "Everything Nothing|14",
  "Absolute Unity|14",
];

K.Headwear = [
  "Paper Hat|0",
  "Shower Cap|0",
  "Hair Net|0",
  "Bandana|0",
  "Headband|0",
  "Scrunchie|0",
  "Hair Clip|0",
  "Bobby Pin|0",
  "Barrette|0",
  "Hair Elastic|0",
  "Baseball Cap|1",
  "Beanie|1",
  "Knit Hat|1",
  "Sun Hat|1",
  "Bucket Hat|1",
  "Trucker Hat|1",
  "Visor|1",
  "Headscarf|1",
  "Turban|1",
  "Beret|1",
  "Hard Hat|2",
  "Construction Helmet|2",
  "Bike Helmet|2",
  "Ski Hat|2",
  "Winter Hat|2",
  "Wool Cap|2",
  "Fleece Hat|2",
  "Ushanka|2",
  "Cowboy Hat|2",
  "Fedora|2",
  "Motorcycle Helmet|3",
  "Sports Helmet|3",
  "Football Helmet|3",
  "Hockey Helmet|3",
  "Baseball Helmet|3",
  "Climbing Helmet|3",
  "Skateboard Helmet|3",
  "Equestrian Helmet|3",
  "Racing Helmet|3",
  "Safety Helmet|3",
  "Military Helmet|4",
  "Combat Helmet|4",
  "Tactical Helmet|4",
  "Kevlar Helmet|4",
  "Ballistic Helmet|4",
  "PASGT Helmet|4",
  "ACH Helmet|4",
  "MICH Helmet|4",
  "Riot Helmet|4",
  "SWAT Helmet|4",
  "Flight Helmet|5",
  "Pilot Helmet|5",
  "Aviator Helmet|5",
  "Astronaut Helmet|5",
  "Space Helmet|5",
  "Pressure Helmet|5",
  "Oxygen Helmet|5",
  "Diving Helmet|5",
  "Hazmat Helmet|5",
  "NBC Helmet|5",
  "Smart Helmet|6",
  "HUD Helmet|6",
  "Heads-Up Display|6",
  "Digital Helmet|6",
  "Tech Helmet|6",
  "Communication Helmet|6",
  "Sensor Helmet|6",
  "Targeting Helmet|6",
  "Tactical Display|6",
  "Info Helmet|6",
  "Neural Helmet|7",
  "Brain Scanner|7",
  "Mind Reader|7",
  "Thought Helmet|7",
  "EEG Helmet|7",
  "Brainwave Monitor|7",
  "Mental Interface|7",
  "Cognitive Helmet|7",
  "Memory Scanner|7",
  "Dream Recorder|7",
  "Cyber Crown|8",
  "Neural Crown|8",
  "Digital Tiara|8",
  "Mind Crown|8",
  "Thought Crown|8",
  "Brain Crown|8",
  "Consciousness Crown|8",
  "Mental Crown|8",
  "Psychic Crown|8",
  "Telepathic Crown|8",
  "Mind Shield|9",
  "Thought Shield|9",
  "Mental Barrier|9",
  "Psychic Shield|9",
  "Brain Shield|9",
  "Neural Shield|9",
  "Consciousness Shield|9",
  "Memory Shield|9",
  "Dream Shield|9",
  "Reality Shield|9",
  "Quantum Headset|10",
  "Dimensional Helmet|10",
  "Space-Time Crown|10",
  "Reality Helmet|10",
  "Universe Crown|10",
  "Multiverse Headset|10",
  "Infinity Crown|10",
  "Cosmic Helmet|10",
  "Void Crown|10",
  "Null Helmet|10",
  "Neural Interface Crown|11",
  "Brain Matrix Crown|11",
  "Mind Network Crown|11",
  "Consciousness Web|11",
  "Thought Network|11",
  "Mental Grid|11",
  "Psychic Matrix|11",
  "Neural Web Crown|11",
  "Mind Mesh Crown|11",
  "Brain Cloud Crown|11",
  "Thought Amplifier|12",
  "Mind Amplifier|12",
  "Brain Amplifier|12",
  "Neural Amplifier|12",
  "Consciousness Amplifier|12",
  "Mental Amplifier|12",
  "Psychic Amplifier|12",
  "Memory Amplifier|12",
  "Dream Amplifier|12",
  "Reality Amplifier|12",
  "Consciousness Projector|13",
  "Mind Projector|13",
  "Thought Projector|13",
  "Brain Projector|13",
  "Neural Projector|13",
  "Mental Projector|13",
  "Psychic Projector|13",
  "Memory Projector|13",
  "Dream Projector|13",
  "Reality Projector|13",
  "Reality Perception Filter|14",
  "Universal Perception|14",
  "Omniscient Crown|14",
  "All-Seeing Crown|14",
  "Divine Perception|14",
  "Cosmic Awareness|14",
  "Absolute Vision|14",
  "Perfect Sight|14",
  "Ultimate Perception|14",
  "Infinite Awareness|14",
];

K.Eyewear = [
  "Reading Glasses|0",
  "Magnifying Glass|0",
  "Monocle|0",
  "Pince-nez|0",
  "Bifocals|0",
  "Cheaters|0",
  "Drugstore Glasses|0",
  "Safety Glasses|0",
  "Clear Glasses|0",
  "Fake Glasses|0",
  "Sunglasses|1",
  "Prescription Glasses|1",
  "Contact Lenses|1",
  "Designer Glasses|1",
  "Fashion Glasses|1",
  "Horn-rimmed Glasses|1",
  "Wire-frame Glasses|1",
  "Plastic Glasses|1",
  "Retro Glasses|1",
  "Vintage Glasses|1",
  "Safety Goggles|2",
  "Swimming Goggles|2",
  "Ski Goggles|2",
  "Lab Goggles|2",
  "Work Goggles|2",
  "Dust Goggles|2",
  "Wind Goggles|2",
  "Motorcycle Goggles|2",
  "Aviator Goggles|2",
  "Steampunk Goggles|2",
  "Welding Mask|3",
  "Welding Goggles|3",
  "Cutting Goggles|3",
  "Grinding Shield|3",
  "Face Shield|3",
  "Plasma Cutting Mask|3",
  "Arc Welding Helmet|3",
  "Gas Welding Goggles|3",
  "TIG Welding Mask|3",
  "MIG Welding Helmet|3",
  "Tactical Goggles|4",
  "Military Goggles|4",
  "Combat Goggles|4",
  "Ballistic Glasses|4",
  "Shooting Glasses|4",
  "Range Glasses|4",
  "Protective Eyewear|4",
  "Impact Glasses|4",
  "Shatterproof Glasses|4",
  "Bulletproof Glasses|4",
  "Night Vision Goggles|5",
  "Thermal Goggles|5",
  "Infrared Goggles|5",
  "Heat Vision Goggles|5",
  "Low Light Goggles|5",
  "Starlight Scope|5",
  "Image Intensifier|5",
  "Gen 1 Night Vision|5",
  "Gen 2 Night Vision|5",
  "Gen 3 Night Vision|5",
  "VR Headset|6",
  "Virtual Reality Goggles|6",
  "3D Glasses|6",
  "Stereoscopic Glasses|6",
  "Polarized 3D Glasses|6",
  "Active Shutter Glasses|6",
  "Anaglyph Glasses|6",
  "Head-mounted Display|6",
  "Immersive Headset|6",
  "Gaming Goggles|6",
  "AR Visor|7",
  "Augmented Reality Glasses|7",
  "Smart Glasses|7",
  "HUD Glasses|7",
  "Heads-up Display|7",
  "Digital Overlay|7",
  "Info Glasses|7",
  "Data Glasses|7",
  "Tech Glasses|7",
  "Cyber Glasses|7",
  "Targeting Monocle|8",
  "Scope Monocle|8",
  "Zoom Monocle|8",
  "Digital Monocle|8",
  "Smart Monocle|8",
  "Tech Monocle|8",
  "Cyber Monocle|8",
  "Neural Monocle|8",
  "Brain Monocle|8",
  "Mind Monocle|8",
  "Cyber Eyes|9",
  "Bionic Eyes|9",
  "Artificial Eyes|9",
  "Synthetic Eyes|9",
  "Digital Eyes|9",
  "Electronic Eyes|9",
  "Robotic Eyes|9",
  "Mechanical Eyes|9",
  "Prosthetic Eyes|9",
  "Replacement Eyes|9",
  "Neural Optics|10",
  "Brain Optics|10",
  "Mind Optics|10",
  "Thought Optics|10",
  "Consciousness Optics|10",
  "Mental Optics|10",
  "Psychic Optics|10",
  "Telepathic Optics|10",
  "Neural Vision|10",
  "Brain Vision|10",
  "Quantum Vision|11",
  "Dimensional Vision|11",
  "Space-Time Vision|11",
  "Reality Vision|11",
  "Universe Vision|11",
  "Multiverse Vision|11",
  "Infinity Vision|11",
  "Cosmic Vision|11",
  "Void Vision|11",
  "Null Vision|11",
  "Reality Scanner|12",
  "Universe Scanner|12",
  "Dimensional Scanner|12",
  "Space-Time Scanner|12",
  "Quantum Scanner|12",
  "Multiverse Scanner|12",
  "Infinity Scanner|12",
  "Cosmic Scanner|12",
  "Void Scanner|12",
  "Null Scanner|12",
  "Dimensional Viewer|13",
  "Reality Viewer|13",
  "Universe Viewer|13",
  "Space-Time Viewer|13",
  "Quantum Viewer|13",
  "Multiverse Viewer|13",
  "Infinity Viewer|13",
  "Cosmic Viewer|13",
  "Void Viewer|13",
  "Null Viewer|13",
  "Temporal Sight|14",
  "Omniscient Lens|14",
  "All-Seeing Eye|14",
  "Divine Vision|14",
  "Perfect Sight|14",
  "Ultimate Vision|14",
  "Absolute Sight|14",
  "Infinite Sight|14",
  "Eternal Vision|14",
  "Godlike Sight|14",
];

K.BodyArmor = [
  "T-Shirt|0",
  "Tank Top|0",
  "Undershirt|0",
  "Thin Shirt|0",
  "Cotton Shirt|0",
  "Polo Shirt|0",
  "Button-up Shirt|0",
  "Dress Shirt|0",
  "Flannel Shirt|0",
  "Jersey|0",
  "Thick Shirt|1",
  "Long Sleeve Shirt|1",
  "Sweatshirt|1",
  "Hoodie|1",
  "Pullover|1",
  "Cardigan|1",
  "Sweater|1",
  "Turtleneck|1",
  "Mock Turtleneck|1",
  "Heavy Shirt|1",
  "Padded Shirt|2",
  "Quilted Shirt|2",
  "Insulated Shirt|2",
  "Work Shirt|2",
  "Utility Shirt|2",
  "Reinforced Shirt|2",
  "Double Layer Shirt|2",
  "Thick Cotton Shirt|2",
  "Canvas Shirt|2",
  "Duck Cloth Shirt|2",
  "Chain Mail Shirt|3",
  "Mesh Armor|3",
  "Wire Mesh Vest|3",
  "Metal Mesh|3",
  "Steel Mesh|3",
  "Aluminum Mesh|3",
  "Titanium Mesh|3",
  "Composite Mesh|3",
  "Fiber Mesh|3",
  "Synthetic Mesh|3",
  "Stab Vest|4",
  "Knife Vest|4",
  "Cut Resistant Vest|4",
  "Slash Proof Vest|4",
  "Puncture Vest|4",
  "Security Vest|4",
  "Guard Vest|4",
  "Prison Vest|4",
  "Corrections Vest|4",
  "Enforcement Vest|4",
  "Bulletproof Vest|5",
  "Ballistic Vest|5",
  "Level IIA Vest|5",
  "Level II Vest|5",
  "Soft Armor|5",
  "Kevlar Vest|5",
  "Body Armor|5",
  "Protective Vest|5",
  "Police Vest|5",
  "Concealable Vest|5",
  "Tactical Vest|6",
  "Level IIIA Vest|6",
  "Plate Carrier|6",
  "Chest Rig|6",
  "Load Bearing Vest|6",
  "Combat Vest|6",
  "Military Vest|6",
  "Assault Vest|6",
  "Battle Vest|6",
  "War Vest|6",
  "Hard Armor|7",
  "Ceramic Plates|7",
  "Steel Plates|7",
  "Trauma Plates|7",
  "Level III Armor|7",
  "Level IV Armor|7",
  "Rifle Plates|7",
  "AP Plates|7",
  "Multi-hit Plates|7",
  "Stand-alone Plates|7",
  "Riot Armor|8",
  "Full Body Armor|8",
  "Bomb Suit|8",
  "EOD Armor|8",
  "Explosive Suit|8",
  "Blast Suit|8",
  "Fragmentation Vest|8",
  "Shrapnel Vest|8",
  "IED Vest|8",
  "Mine Suit|8",
  "Combat Armor|9",
  "Military Armor|9",
  "Powered Vest|9",
  "Exoskeleton Vest|9",
  "Servo Armor|9",
  "Augmented Vest|9",
  "Enhanced Armor|9",
  "Boosted Vest|9",
  "Amplified Armor|9",
  "Strength Suit|9",
  "Power Armor|10",
  "Mech Suit|10",
  "Robotic Armor|10",
  "Cyborg Suit|10",
  "Android Armor|10",
  "Machine Vest|10",
  "Synthetic Armor|10",
  "Artificial Vest|10",
  "Digital Armor|10",
  "Electronic Vest|10",
  "Nano Armor|11",
  "Smart Armor|11",
  "Adaptive Vest|11",
  "Self-repairing Armor|11",
  "Morphing Vest|11",
  "Shape-shifting Armor|11",
  "Liquid Armor|11",
  "Fluid Vest|11",
  "Programmable Armor|11",
  "Dynamic Vest|11",
  "Energy Shield|12",
  "Force Field|12",
  "Barrier Vest|12",
  "Shield Generator|12",
  "Deflector Armor|12",
  "Protective Field|12",
  "Energy Barrier|12",
  "Force Armor|12",
  "Shield Vest|12",
  "Field Armor|12",
  "Plasma Barrier|13",
  "Fusion Shield|13",
  "Nuclear Vest|13",
  "Atomic Armor|13",
  "Quantum Shield|13",
  "Particle Barrier|13",
  "Photon Armor|13",
  "Wave Shield|13",
  "Field Vest|13",
  "Energy Armor|13",
  "Quantum Armor|14",
  "Reality Plating|14",
  "Dimensional Armor|14",
  "Space-Time Vest|14",
  "Universe Armor|14",
  "Multiverse Vest|14",
  "Infinity Armor|14",
  "Cosmic Vest|14",
  "Void Armor|14",
  "Invulnerability Field|14",
];

K.Jackets = [
  "Windbreaker|0",
  "Track Jacket|0",
  "Shell Jacket|0",
  "Rain Jacket|0",
  "Nylon Jacket|0",
  "Polyester Jacket|0",
  "Mesh Jacket|0",
  "Lightweight Jacket|0",
  "Summer Jacket|0",
  "Thin Jacket|0",
  "Hoodie|1",
  "Zip-up Hoodie|1",
  "Pullover Hoodie|1",
  "Sweatshirt Jacket|1",
  "Fleece Jacket|1",
  "Cotton Jacket|1",
  "Casual Jacket|1",
  "College Jacket|1",
  "Varsity Jacket|1",
  "Letterman Jacket|1",
  "Jean Jacket|2",
  "Denim Jacket|2",
  "Trucker Jacket|2",
  "Corduroy Jacket|2",
  "Canvas Jacket|2",
  "Work Jacket|2",
  "Utility Jacket|2",
  "Field Jacket|2",
  "Chore Jacket|2",
  "Duck Jacket|2",
  "Bomber Jacket|3",
  "Flight Jacket|3",
  "MA-1 Jacket|3",
  "Aviator Jacket|3",
  "Pilot Jacket|3",
  "Military Jacket|3",
  "Army Jacket|3",
  "Navy Jacket|3",
  "Air Force Jacket|3",
  "Marines Jacket|3",
  "Leather Jacket|4",
  "Motorcycle Jacket|4",
  "Biker Jacket|4",
  "Racing Jacket|4",
  "Riding Jacket|4",
  "Moto Jacket|4",
  "Cafe Racer|4",
  "Cruiser Jacket|4",
  "Sport Bike Jacket|4",
  "Touring Jacket|4",
  "Trench Coat|5",
  "Overcoat|5",
  "Pea Coat|5",
  "Wool Coat|5",
  "Winter Coat|5",
  "Heavy Coat|5",
  "Long Coat|5",
  "Dress Coat|5",
  "Formal Coat|5",
  "Business Coat|5",
  "Military Jacket|6",
  "Tactical Jacket|6",
  "Combat Jacket|6",
  "BDU Jacket|6",
  "ACU Jacket|6",
  "Uniform Jacket|6",
  "Service Jacket|6",
  "Dress Uniform|6",
  "Ceremonial Jacket|6",
  "Parade Jacket|6",
  "Kevlar Jacket|7",
  "Ballistic Jacket|7",
  "Protective Jacket|7",
  "Armored Jacket|7",
  "Reinforced Jacket|7",
  "Security Jacket|7",
  "Police Jacket|7",
  "SWAT Jacket|7",
  "Tactical Coat|7",
  "Combat Coat|7",
  "Smart Jacket|8",
  "Tech Jacket|8",
  "Digital Jacket|8",
  "Electronic Jacket|8",
  "Wired Jacket|8",
  "Connected Jacket|8",
  "Sensor Jacket|8",
  "Monitor Jacket|8",
  "Data Jacket|8",
  "Info Jacket|8",
  "Climate Suit|9",
  "Environmental Suit|9",
  "Hazmat Suit|9",
  "Chemical Suit|9",
  "Radiation Suit|9",
  "Bio Suit|9",
  "NBC Suit|9",
  "Containment Suit|9",
  "Isolation Suit|9",
  "Protection Suit|9",
  "Power Coat|10",
  "Exo Jacket|10",
  "Servo Coat|10",
  "Mechanical Jacket|10",
  "Robotic Coat|10",
  "Cyborg Jacket|10",
  "Android Coat|10",
  "Machine Jacket|10",
  "Synthetic Coat|10",
  "Artificial Jacket|10",
  "Nano Jacket|11",
  "Smart Coat|11",
  "Adaptive Jacket|11",
  "Morphing Coat|11",
  "Shape-shift Jacket|11",
  "Liquid Coat|11",
  "Fluid Jacket|11",
  "Programmable Coat|11",
  "Dynamic Jacket|11",
  "Responsive Coat|11",
  "Energy Cloak|12",
  "Force Coat|12",
  "Shield Jacket|12",
  "Barrier Cloak|12",
  "Field Coat|12",
  "Deflector Jacket|12",
  "Protective Cloak|12",
  "Energy Jacket|12",
  "Power Cloak|12",
  "Force Field Coat|12",
  "Stealth Coat|13",
  "Invisibility Cloak|13",
  "Cloaking Jacket|13",
  "Phase Coat|13",
  "Ghost Jacket|13",
  "Shadow Cloak|13",
  "Vanishing Coat|13",
  "Camouflage Jacket|13",
  "Concealment Cloak|13",
  "Hidden Coat|13",
  "Phase Jacket|14",
  "Quantum Cloak|14",
  "Dimensional Wrap|14",
  "Reality Shroud|14",
  "Universe Cloak|14",
  "Multiverse Wrap|14",
  "Infinity Cloak|14",
  "Cosmic Jacket|14",
  "Void Cloak|14",
  "Null Jacket|14",
];

K.Gloves = [
  "Latex Gloves|0",
  "Rubber Gloves|0",
  "Disposable Gloves|0",
  "Plastic Gloves|0",
  "Vinyl Gloves|0",
  "Nitrile Gloves|0",
  "Medical Gloves|0",
  "Surgical Gloves|0",
  "Exam Gloves|0",
  "Food Service Gloves|0",
  "Cotton Gloves|1",
  "Cloth Gloves|1",
  "Fabric Gloves|1",
  "Knit Gloves|1",
  "Wool Gloves|1",
  "Winter Gloves|1",
  "Mittens|1",
  "Fingerless Gloves|1",
  "Half-finger Gloves|1",
  "Casual Gloves|1",
  "Work Gloves|2",
  "Gardening Gloves|2",
  "Utility Gloves|2",
  "Construction Gloves|2",
  "Mechanic Gloves|2",
  "Tool Gloves|2",
  "Grip Gloves|2",
  "Labor Gloves|2",
  "Heavy Duty Gloves|2",
  "Industrial Gloves|2",
  "Driving Gloves|3",
  "Racing Gloves|3",
  "Motorcycle Gloves|3",
  "Biker Gloves|3",
  "Riding Gloves|3",
  "Sport Gloves|3",
  "Athletic Gloves|3",
  "Fitness Gloves|3",
  "Gym Gloves|3",
  "Training Gloves|3",
  "Leather Gloves|4",
  "Cowhide Gloves|4",
  "Suede Gloves|4",
  "Deerskin Gloves|4",
  "Sheepskin Gloves|4",
  "Goatskin Gloves|4",
  "Dress Gloves|4",
  "Formal Gloves|4",
  "Fashion Gloves|4",
  "Luxury Gloves|4",
  "Ski Gloves|5",
  "Snow Gloves|5",
  "Insulated Gloves|5",
  "Thermal Gloves|5",
  "Heated Gloves|5",
  "Waterproof Gloves|5",
  "Weather Gloves|5",
  "Outdoor Gloves|5",
  "Hiking Gloves|5",
  "Climbing Gloves|5",
  "Tactical Gloves|6",
  "Military Gloves|6",
  "Combat Gloves|6",
  "Police Gloves|6",
  "SWAT Gloves|6",
  "Security Gloves|6",
  "Enforcement Gloves|6",
  "Duty Gloves|6",
  "Service Gloves|6",
  "Patrol Gloves|6",
  "Kevlar Gloves|7",
  "Cut Resistant Gloves|7",
  "Slash Proof Gloves|7",
  "Puncture Resistant|7",
  "Knife Proof Gloves|7",
  "Ballistic Gloves|7",
  "Protective Gloves|7",
  "Safety Gloves|7",
  "Reinforced Gloves|7",
  "Armored Gloves|7",
  "Smart Gloves|8",
  "Tech Gloves|8",
  "Digital Gloves|8",
  "Electronic Gloves|8",
  "Sensor Gloves|8",
  "Data Gloves|8",
  "Input Gloves|8",
  "Interface Gloves|8",
  "Control Gloves|8",
  "Haptic Gloves|8",
  "Grip Enhancers|9",
  "Strength Gloves|9",
  "Power Gloves|9",
  "Amplified Gloves|9",
  "Enhanced Gloves|9",
  "Boosted Gloves|9",
  "Augmented Gloves|9",
  "Servo Gloves|9",
  "Mechanical Gloves|9",
  "Robotic Gloves|9",
  "Power Gloves|10",
  "Exo Gloves|10",
  "Cyber Gauntlets|10",
  "Mech Gloves|10",
  "Android Gloves|10",
  "Cyborg Gloves|10",
  "Machine Gloves|10",
  "Synthetic Gloves|10",
  "Artificial Gloves|10",
  "Digital Gauntlets|10",
  "Neural Gloves|11",
  "Brain Gloves|11",
  "Mind Gloves|11",
  "Thought Gloves|11",
  "Mental Gloves|11",
  "Psychic Gloves|11",
  "Telepathic Gloves|11",
  "Consciousness Gloves|11",
  "Memory Gloves|11",
  "Dream Gloves|11",
  "Quantum Mitts|12",
  "Dimensional Gloves|12",
  "Space-Time Gloves|12",
  "Reality Gloves|12",
  "Universe Gloves|12",
  "Multiverse Gloves|12",
  "Infinity Gloves|12",
  "Cosmic Gloves|12",
  "Void Gloves|12",
  "Null Gloves|12",
  "Phase Gloves|13",
  "Ghost Gloves|13",
  "Shadow Gloves|13",
  "Ethereal Gloves|13",
  "Spectral Gloves|13",
  "Spirit Gloves|13",
  "Phantom Gloves|13",
  "Wraith Gloves|13",
  "Invisible Gloves|13",
  "Translucent Gloves|13",
  "Reality Manipulators|14",
  "Universe Handlers|14",
  "Cosmic Manipulators|14",
  "Dimensional Handlers|14",
  "Space-Time Manipulators|14",
  "Quantum Handlers|14",
  "Infinity Manipulators|14",
  "Void Handlers|14",
  "Null Manipulators|14",
  "Omnipotent Grasp|14",
];

K.Wristwear = [
  "Cloth Band|0",
  "Fabric Band|0",
  "String Bracelet|0",
  "Rubber Band|0",
  "Hair Tie|0",
  "Elastic Band|0",
  "Friendship Bracelet|0",
  "Thread Bracelet|0",
  "Yarn Bracelet|0",
  "Rope Bracelet|0",
  "Leather Band|1",
  "Wristband|1",
  "Sweatband|1",
  "Sports Band|1",
  "Silicone Band|1",
  "Rubber Bracelet|1",
  "Charity Bracelet|1",
  "ID Bracelet|1",
  "Medical Bracelet|1",
  "Alert Bracelet|1",
  "Digital Watch|2",
  "Casio Watch|2",
  "Timex Watch|2",
  "Basic Watch|2",
  "Quartz Watch|2",
  "LCD Watch|2",
  "LED Watch|2",
  "Calculator Watch|2",
  "Alarm Watch|2",
  "Stopwatch|2",
  "Sports Watch|3",
  "Running Watch|3",
  "Fitness Watch|3",
  "Athletic Watch|3",
  "Training Watch|3",
  "Exercise Watch|3",
  "Workout Watch|3",
  "Performance Watch|3",
  "Activity Watch|3",
  "Health Watch|3",
  "Smart Watch|4",
  "Apple Watch|4",
  "Samsung Watch|4",
  "Fitbit|4",
  "Garmin Watch|4",
  "Wear OS Watch|4",
  "Hybrid Watch|4",
  "Connected Watch|4",
  "Digital Assistant|4",
  "Notification Watch|4",
  "Fitness Tracker|5",
  "Heart Rate Monitor|5",
  "Step Counter|5",
  "Calorie Tracker|5",
  "Sleep Monitor|5",
  "Health Monitor|5",
  "Activity Tracker|5",
  "Wellness Tracker|5",
  "Biometric Monitor|5",
  "Vital Signs Monitor|5",
  "Tactical Watch|6",
  "Military Watch|6",
  "Field Watch|6",
  "Combat Watch|6",
  "Survival Watch|6",
  "Outdoor Watch|6",
  "GPS Watch|6",
  "Navigation Watch|6",
  "Compass Watch|6",
  "Altimeter Watch|6",
  "Bio Monitor|7",
  "Medical Monitor|7",
  "Health Scanner|7",
  "Vital Monitor|7",
  "Blood Monitor|7",
  "Pulse Monitor|7",
  "Oxygen Monitor|7",
  "Temperature Monitor|7",
  "Pressure Monitor|7",
  "Glucose Monitor|7",
  "Neural Link|8",
  "Brain Interface|8",
  "Mind Monitor|8",
  "Thought Tracker|8",
  "Mental Interface|8",
  "Consciousness Monitor|8",
  "Brainwave Monitor|8",
  "EEG Tracker|8",
  "Neural Scanner|8",
  "Mind Scanner|8",
  "Quantum Timer|9",
  "Atomic Clock|9",
  "Precision Timer|9",
  "Quantum Watch|9",
  "Temporal Monitor|9",
  "Time Tracker|9",
  "Chronometer|9",
  "Time Keeper|9",
  "Duration Monitor|9",
  "Interval Timer|9",
  "Cyber Interface|10",
  "Digital Interface|10",
  "Data Interface|10",
  "Network Interface|10",
  "System Interface|10",
  "Computer Interface|10",
  "Tech Interface|10",
  "Electronic Interface|10",
  "Virtual Interface|10",
  "Synthetic Interface|10",
  "Mind Bridge|11",
  "Neural Bridge|11",
  "Brain Bridge|11",
  "Thought Bridge|11",
  "Mental Bridge|11",
  "Consciousness Bridge|11",
  "Psychic Bridge|11",
  "Telepathic Bridge|11",
  "Mind Link|11",
  "Neural Connection|11",
  "Temporal Controller|12",
  "Time Controller|12",
  "Chronos Controller|12",
  "Time Manipulator|12",
  "Temporal Manipulator|12",
  "Time Adjuster|12",
  "Chronometer Controller|12",
  "Duration Controller|12",
  "Time Flow Controller|12",
  "Temporal Flow Monitor|12",
  "Reality Sync|13",
  "Universe Sync|13",
  "Dimensional Sync|13",
  "Space-Time Sync|13",
  "Quantum Sync|13",
  "Multiverse Sync|13",
  "Infinity Sync|13",
  "Cosmic Sync|13",
  "Void Sync|13",
  "Null Sync|13",
  "Dimensional Anchor|14",
  "Reality Anchor|14",
  "Universe Anchor|14",
  "Space-Time Anchor|14",
  "Quantum Anchor|14",
  "Multiverse Anchor|14",
  "Infinity Anchor|14",
  "Cosmic Anchor|14",
  "Void Anchor|14",
  "Infinity Band|14",
];

K.Belts = [
  "Rope Belt|0",
  "String Belt|0",
  "Yarn Belt|0",
  "Cord Belt|0",
  "Twine Belt|0",
  "Fabric Strip|0",
  "Cloth Belt|0",
  "Ribbon Belt|0",
  "Elastic Band|0",
  "Rubber Band|0",
  "Cloth Belt|1",
  "Cotton Belt|1",
  "Fabric Belt|1",
  "Canvas Belt|1",
  "Web Belt|1",
  "Nylon Belt|1",
  "Polyester Belt|1",
  "Woven Belt|1",
  "Braided Belt|1",
  "Sash Belt|1",
  "Leather Belt|2",
  "Cowhide Belt|2",
  "Suede Belt|2",
  "Dress Belt|2",
  "Casual Belt|2",
  "Brown Belt|2",
  "Black Belt|2",
  "Work Belt|2",
  "Basic Belt|2",
  "Simple Belt|2",
  "Utility Belt|3",
  "Tool Belt|3",
  "Work Belt|3",
  "Construction Belt|3",
  "Carpenter Belt|3",
  "Mechanic Belt|3",
  "Electrician Belt|3",
  "Plumber Belt|3",
  "Handyman Belt|3",
  "Tradesman Belt|3",
  "Tactical Belt|4",
  "Military Belt|4",
  "Combat Belt|4",
  "Police Belt|4",
  "Security Belt|4",
  "Duty Belt|4",
  "Service Belt|4",
  "Patrol Belt|4",
  "Enforcement Belt|4",
  "Officer Belt|4",
  "Gun Belt|5",
  "Holster Belt|5",
  "Weapon Belt|5",
  "Pistol Belt|5",
  "Ammo Belt|5",
  "Cartridge Belt|5",
  "Bandolier|5",
  "Magazine Belt|5",
  "Clip Belt|5",
  "Round Belt|5",
  "Equipment Belt|6",
  "Gear Belt|6",
  "Load Belt|6",
  "Harness Belt|6",
  "Rigger Belt|6",
  "Climbing Belt|6",
  "Safety Belt|6",
  "Rescue Belt|6",
  "Rappel Belt|6",
  "Mountaineering Belt|6",
  "Smart Belt|7",
  "Tech Belt|7",
  "Digital Belt|7",
  "Electronic Belt|7",
  "Sensor Belt|7",
  "Monitor Belt|7",
  "Data Belt|7",
  "Info Belt|7",
  "Tracking Belt|7",
  "GPS Belt|7",
  "Power Belt|8",
  "Energy Belt|8",
  "Battery Belt|8",
  "Charging Belt|8",
  "Electric Belt|8",
  "Powered Belt|8",
  "Energized Belt|8",
  "Voltage Belt|8",
  "Current Belt|8",
  "Electrical Belt|8",
  "Cyber Belt|9",
  "Neural Belt|9",
  "Brain Belt|9",
  "Mind Belt|9",
  "Thought Belt|9",
  "Mental Belt|9",
  "Consciousness Belt|9",
  "Psychic Belt|9",
  "Telepathic Belt|9",
  "Interface Belt|9",
  "Quantum Belt|10",
  "Atomic Belt|10",
  "Particle Belt|10",
  "Photon Belt|10",
  "Wave Belt|10",
  "Field Belt|10",
  "Force Belt|10",
  "Gravity Belt|10",
  "Magnetic Belt|10",
  "Electromagnetic Belt|10",
  "Dimensional Belt|11",
  "Space Belt|11",
  "Time Belt|11",
  "Space-Time Belt|11",
  "Temporal Belt|11",
  "Chronos Belt|11",
  "Warp Belt|11",
  "Portal Belt|11",
  "Teleport Belt|11",
  "Transport Belt|11",
  "Reality Belt|12",
  "Universe Belt|12",
  "Cosmic Belt|12",
  "Galactic Belt|12",
  "Stellar Belt|12",
  "Solar Belt|12",
  "Planetary Belt|12",
  "Orbital Belt|12",
  "Celestial Belt|12",
  "Astral Belt|12",
  "Multiverse Belt|13",
  "Infinity Belt|13",
  "Eternal Belt|13",
  "Perpetual Belt|13",
  "Endless Belt|13",
  "Limitless Belt|13",
  "Boundless Belt|13",
  "Infinite Belt|13",
  "Absolute Belt|13",
  "Ultimate Belt|13",
  "Void Belt|14",
  "Null Belt|14",
  "Empty Belt|14",
  "Nothingness Belt|14",
  "Zero Belt|14",
  "Blank Belt|14",
  "Hollow Belt|14",
  "Vacant Belt|14",
  "Absent Belt|14",
  "Omnipotent Sash|14",
];

K.Legwear = [
  "Pajama Pants|0",
  "Sweatpants|0",
  "Lounge Pants|0",
  "Sleep Pants|0",
  "Track Pants|0",
  "Yoga Pants|0",
  "Leggings|0",
  "Tights|0",
  "Shorts|0",
  "Gym Shorts|0",
  "Jeans|1",
  "Denim Pants|1",
  "Blue Jeans|1",
  "Casual Pants|1",
  "Khakis|1",
  "Chinos|1",
  "Cotton Pants|1",
  "Dress Pants|1",
  "Slacks|1",
  "Trousers|1",
  "Cargo Pants|2",
  "Work Pants|2",
  "Utility Pants|2",
  "Canvas Pants|2",
  "Duck Pants|2",
  "Carpenter Pants|2",
  "Mechanic Pants|2",
  "Coveralls|2",
  "Overalls|2",
  "Jumpsuit|2",
  "Tactical Pants|3",
  "Military Pants|3",
  "Combat Pants|3",
  "BDU Pants|3",
  "ACU Pants|3",
  "Camouflage Pants|3",
  "Fatigues|3",
  "Service Pants|3",
  "Field Pants|3",
  "Battle Pants|3",
  "Reinforced Pants|4",
  "Padded Pants|4",
  "Protective Pants|4",
  "Safety Pants|4",
  "Cut Resistant Pants|4",
  "Slash Proof Pants|4",
  "Puncture Pants|4",
  "Heavy Duty Pants|4",
  "Industrial Pants|4",
  "Hazard Pants|4",
  "Armored Pants|5",
  "Kevlar Pants|5",
  "Ballistic Pants|5",
  "Bullet Resistant|5",
  "Stab Proof Pants|5",
  "Combat Trousers|5",
  "Tactical Trousers|5",
  "Military Trousers|5",
  "Security Pants|5",
  "Police Pants|5",
  "Riot Pants|6",
  "SWAT Pants|6",
  "EOD Pants|6",
  "Bomb Squad Pants|6",
  "Explosive Pants|6",
  "Blast Pants|6",
  "Fragmentation Pants|6",
  "Shrapnel Pants|6",
  "IED Pants|6",
  "Mine Pants|6",
  "Smart Pants|7",
  "Tech Pants|7",
  "Digital Pants|7",
  "Electronic Pants|7",
  "Sensor Pants|7",
  "Monitor Pants|7",
  "Data Pants|7",
  "Info Pants|7",
  "Tracking Pants|7",
  "GPS Pants|7",
  "Tech Leggings|8",
  "Smart Leggings|8",
  "Digital Leggings|8",
  "Electronic Leggings|8",
  "Sensor Leggings|8",
  "Monitor Leggings|8",
  "Data Leggings|8",
  "Info Leggings|8",
  "Tracking Leggings|8",
  "Bio Leggings|8",
  "Power Pants|9",
  "Exo Pants|9",
  "Servo Pants|9",
  "Mechanical Pants|9",
  "Robotic Pants|9",
  "Enhanced Pants|9",
  "Augmented Pants|9",
  "Boosted Pants|9",
  "Amplified Pants|9",
  "Strength Pants|9",
  "Cyber Legs|10",
  "Bionic Legs|10",
  "Artificial Legs|10",
  "Synthetic Legs|10",
  "Digital Legs|10",
  "Electronic Legs|10",
  "Robotic Legs|10",
  "Machine Legs|10",
  "Android Legs|10",
  "Cyborg Legs|10",
  "Neural Pants|11",
  "Brain Pants|11",
  "Mind Pants|11",
  "Thought Pants|11",
  "Mental Pants|11",
  "Consciousness Pants|11",
  "Psychic Pants|11",
  "Telepathic Pants|11",
  "Interface Pants|11",
  "Neural Leggings|11",
  "Quantum Legwear|12",
  "Atomic Pants|12",
  "Particle Pants|12",
  "Photon Pants|12",
  "Wave Pants|12",
  "Field Pants|12",
  "Force Pants|12",
  "Energy Pants|12",
  "Plasma Pants|12",
  "Fusion Pants|12",
  "Phase Pants|13",
  "Ghost Pants|13",
  "Shadow Pants|13",
  "Ethereal Pants|13",
  "Spectral Pants|13",
  "Spirit Pants|13",
  "Phantom Pants|13",
  "Wraith Pants|13",
  "Invisible Pants|13",
  "Translucent Pants|13",
  "Reality Legs|14",
  "Universe Pants|14",
  "Dimensional Pants|14",
  "Space-Time Pants|14",
  "Cosmic Pants|14",
  "Multiverse Pants|14",
  "Infinity Pants|14",
  "Void Leggings|14",
  "Null Pants|14",
  "Omnipotent Legs|14",
];

K.Footwear = [
  "Flip Flops|0",
  "Sandals|0",
  "Slippers|0",
  "Slides|0",
  "Thongs|0",
  "Clogs|0",
  "Crocs|0",
  "House Shoes|0",
  "Bedroom Slippers|0",
  "Foam Sandals|0",
  "Sneakers|1",
  "Running Shoes|1",
  "Tennis Shoes|1",
  "Athletic Shoes|1",
  "Trainers|1",
  "Cross Trainers|1",
  "Walking Shoes|1",
  "Casual Shoes|1",
  "Canvas Shoes|1",
  "Converse|1",
  "Work Boots|2",
  "Construction Boots|2",
  "Steel Toe Boots|2",
  "Safety Boots|2",
  "Work Shoes|2",
  "Industrial Boots|2",
  "Composite Toe|2",
  "Slip Resistant|2",
  "Non-slip Shoes|2",
  "Safety Shoes|2",
  "Hiking Boots|3",
  "Outdoor Boots|3",
  "Trail Boots|3",
  "Mountain Boots|3",
  "Trekking Boots|3",
  "Backpacking Boots|3",
  "Waterproof Boots|3",
  "All Terrain Boots|3",
  "Rugged Boots|3",
  "Adventure Boots|3",
  "Combat Boots|4",
  "Military Boots|4",
  "Army Boots|4",
  "Tactical Boots|4",
  "Service Boots|4",
  "Duty Boots|4",
  "Field Boots|4",
  "Battle Boots|4",
  "War Boots|4",
  "Soldier Boots|4",
  "Steel Toes|5",
  "Reinforced Boots|5",
  "Armored Boots|5",
  "Protected Boots|5",
  "Shielded Boots|5",
  "Fortified Boots|5",
  "Heavy Duty Boots|5",
  "Industrial Boots|5",
  "Safety Boots|5",
  "Protective Boots|5",
  "Tactical Boots|6",
  "SWAT Boots|6",
  "Police Boots|6",
  "Security Boots|6",
  "Enforcement Boots|6",
  "Patrol Boots|6",
  "Officer Boots|6",
  "Law Enforcement|6",
  "Riot Boots|6",
  "Special Forces|6",
  "Military Boots|7",
  "Jump Boots|7",
  "Paratrooper Boots|7",
  "Airborne Boots|7",
  "Ranger Boots|7",
  "Special Ops Boots|7",
  "Elite Boots|7",
  "Commando Boots|7",
  "Spec Ops Boots|7",
  "Black Ops Boots|7",
  "Armored Boots|8",
  "Ballistic Boots|8",
  "Kevlar Boots|8",
  "Bulletproof Boots|8",
  "Blast Boots|8",
  "Explosive Boots|8",
  "Fragmentation Boots|8",
  "Shrapnel Boots|8",
  "IED Boots|8",
  "Mine Boots|8",
  "Smart Shoes|9",
  "Tech Boots|9",
  "Digital Shoes|9",
  "Electronic Boots|9",
  "Sensor Shoes|9",
  "Monitor Boots|9",
  "Data Shoes|9",
  "Info Boots|9",
  "Tracking Shoes|9",
  "GPS Boots|9",
  "Hover Boots|10",
  "Anti-gravity Boots|10",
  "Levitation Boots|10",
  "Flying Boots|10",
  "Floating Shoes|10",
  "Weightless Boots|10",
  "Gravity Boots|10",
  "Magnetic Boots|10",
  "Repulsor Boots|10",
  "Jet Boots|10",
  "Power Boots|11",
  "Exo Boots|11",
  "Servo Boots|11",
  "Mechanical Boots|11",
  "Robotic Boots|11",
  "Enhanced Boots|11",
  "Augmented Boots|11",
  "Boosted Boots|11",
  "Amplified Boots|11",
  "Strength Boots|11",
  "Cyber Feet|12",
  "Bionic Feet|12",
  "Artificial Feet|12",
  "Synthetic Feet|12",
  "Digital Feet|12",
  "Electronic Feet|12",
  "Robotic Feet|12",
  "Machine Feet|12",
  "Android Feet|12",
  "Cyborg Feet|12",
  "Neural Soles|13",
  "Brain Boots|13",
  "Mind Shoes|13",
  "Thought Boots|13",
  "Mental Shoes|13",
  "Consciousness Boots|13",
  "Psychic Shoes|13",
  "Telepathic Boots|13",
  "Interface Shoes|13",
  "Neural Boots|13",
  "Quantum Boots|14",
  "Phase Walkers|14",
  "Reality Steppers|14",
  "Dimensional Boots|14",
  "Space-Time Shoes|14",
  "Universe Boots|14",
  "Multiverse Shoes|14",
  "Infinity Boots|14",
  "Cosmic Shoes|14",
  "Omnipresent Shoes|14",
];

K.Armors = [
  "Lace|1",
  "Macrame|2",
  "Burlap|3",
  "Canvas|4",
  "Flannel|5",
  "Chamois|6",
  "Pleathers|7",
  "Leathers|8",
  "Bearskin|9",
  "Ringmail|10",
  "Scale Mail|12",
  "Chainmail|14",
  "Splint Mail|15",
  "Platemail|16",
  "ABS|17",
  "Kevlar|18",
  "Titanium|19",
  "Mithril Mail|20",
  "Diamond Mail|25",
  "Plasma|30",
];

K.Weapons = [
  "Pool Noodle|0",
  "Rotten Banana Peel|0",
  "Rubber Chicken|0",
  "Foam Finger|0",
  "Balloon Sword|0",
  "Fly Swatter|0",
  "Windshield Wiper|0",
  "Rubber Band|0",
  "Oven Mitt|0",
  "Bubble Wand|0",
  "Foam LARPing Sword|1",
  "Dust Pan|1",
  "Cool Stick|1",
  "Stale Baguette|1",
  "Plastic Spork|1",
  "Toilet Plunger|1",
  "Pool Cue|2",
  "Baseball Bat|2",
  "Golf Club|2",
  "Tire Iron|3",
  "Ice Pick|4",
  "Nail Gun|4",
  "Ball-peen Hammer|3",
  "Chainsaw|4",
  "Razor Blade|4",
  "Weed Whacker|3",
  "Flare Gun|5",
  "Tranquilizer|5",
  "Potato Cannon|5",
  "Crossbow|5",
  "Compound Bow|5",
  "9mm Pistol|6",
  ".38 Special|6",
  "Glock 17|6",
  "Makarov|6",
  ".45 ACP|7",
  "Desert Eagle|7",
  "AK-47|7",
  "SPAS-12|7",
  "SKS|7",
  "Barrett M82|8",
  "AWP|8",
  "M79 Grenade Launcher|9",
  "Rail Gun Prototype|9",
  "RPG-7|10",
  "Bazooka|10",
  "Spatula|1",
  "Encyclopedia|1",
  "Umbrella|1",
  "Dodgeball|1",
  "Butter Knife|2",
  "Rolling Pin|2",
  "Stapler|2",
  "Metal Fork|2",
  "Christmas Ornaments in a Sock|2",
  "Walking Stick|2",
  "Bowling Ball|2",
  "Staple Gun|3",
  "Pitchfork|3",
  "Weed Whacker|3",
  "Crowbar|4",
  "Blowtorch|3",
  "Sledgehammer|3",
  "Pencil|3",
  "Croquet Mallot|3",
  "Nunchucks|4",
  "Brass Knuckles|4",
  "Taser|4",
  "Switchblade|4",
  "Bowie Knife|4",
  ".22 Pistol|5",
  "Derringer|5",
  ".22 Rifle|5",
  "Medieval Trebuchet|5",
  "BB Gun|5",
  "H&K USP|6",
  "Beretta 92|6",
  "Bolt Action Rifle|6",
  "Snubnose Revolver|6",
  ".30-06 Rifle|6",
  "Mossberg 500|6",
  "Mini-14|7",
  "MAC-10|7",
  "Tommy Gun|7",
  "FN FAL|7",
  "Grease Gun|7",
  "SR-25|8",
  "Anti-Material Rifle|8",
  "SCAR-H|8",
  "AA-12|8",
  "M249|8",
  "PKP|8",
  "Steyr Scout|8",
  "Negev|8",
  "BAR|9",
  "McMillan TAC-50|9",
  "PKM|9",
  "Harpoon Gun|9",
  "Pirate Ship Cannon|9",
  "XM25|9",
  "RPK|9",
  "M60|9",
  "M224 Mortar|10",
  "M242 Bushmaster|10",
  "M134 Minigun|10",
];

K.Specials = [
  "Diadem",
  "Festoon",
  "Gemstone",
  "Phial",
  "Tiara",
  "Scabbard",
  "Arrow",
  "Lens",
  "Lamp",
  "Hymnal",
  "Fleece",
  "Laurel",
  "Brooch",
  "Gimlet",
  "Cobble",
  "Albatross",
  "Brazier",
  "Bandolier",
  "Tome",
  "Garnet",
  "Amethyst",
  "Candelabra",
  "Corset",
  "Sphere",
  "Sceptre",
  "Ankh",
  "Talisman",
  "Orb",
  "Gammel",
  "Ornament",
  "Brocade",
  "Galoon",
  "Bijou",
  "Spangle",
  "Gimcrack",
  "Hood",
  "Vulpeculum",
];

K.ItemAttrib = [
  "Golden",
  "Gilded",
  "Spectral",
  "Astral",
  "Garlanded",
  "Precious",
  "Crafted",
  "Dual",
  "Filigreed",
  "Cruciate",
  "Arcane",
  "Blessed",
  "Reverential",
  "Lucky",
  "Enchanted",
  "Gleaming",
  "Grandiose",
  "Sacred",
  "Legendary",
  "Mythic",
  "Crystalline",
  "Austere",
  "Ostentatious",
  "One True",
  "Proverbial",
  "Fearsome",
  "Deadly",
  "Benevolent",
  "Unearthly",
  "Magnificent",
  "Iron",
  "Ormolu",
  "Puissant",
];

K.ItemOfs = [
  "Foreboding",
  "Foreshadowing",
  "Nervousness",
  "Happiness",
  "Torpor",
  "Danger",
  "Craft",
  "Silence",
  "Invisibility",
  "Rapidity",
  "Pleasure",
  "Practicality",
  "Hurting",
  "Joy",
  "Petulance",
  "Intrusion",
  "Chaos",
  "Suffering",
  "Extroversion",
  "Frenzy",
  "Sisu",
  "Solitude",
  "Punctuality",
  "Efficiency",
  "Comfort",
  "Patience",
  "Internment",
  "Incarceration",
  "Misapprehension",
  "Loyalty",
  "Envy",
  "Acrimony",
  "Worry",
  "Fear",
  "Awe",
  "Guile",
  "Prurience",
  "Fortune",
  "Perspicacity",
  "Domination",
  "Submission",
  "Fealty",
  "Hunger",
  "Despair",
  "Cruelty",
  "Grob",
  "Dignard",
  "Ra",
  "the Bone",
  "Diamonique",
  "Electrum",
  "Hydragyrum",
];

K.BoringItems = [
  "nail",
  "lunchpail",
  "sock",
  "I.O.U.",
  "cookie",
  "pint",
  "toothpick",
  "writ",
  "newspaper",
  "letter",
  "plank",
  "hat",
  "egg",
  "coin",
  "needle",
  "bucket",
  "ladder",
  "chicken",
  "twig",
  "dirtclod",
  "counterpane",
  "vest",
  "teratoma",
  "bunny",
  "rock",
  "pole",
  "carrot",
  "canoe",
  "inkwell",
  "hoe",
  "bandage",
  "trowel",
  "towel",
  "planter box",
  "anvil",
  "axle",
  "tuppence",
  "casket",
  "nosegay",
  "trinket",
  "credenza",
  "writ",
];

K.Monsters = [
  "Anhkheg|6|chitin",
  "Ant|0|antenna",
  "Ape|4|ass",
  "Baluchitherium|14|ear",
  "Beholder|10|eyestalk",
  "Black Pudding|10|saliva",
  "Blink Dog|4|eyelid",
  "Cub Scout|1|neckerchief",
  "Girl Scout|2|cookie",
  "Boy Scout|3|merit badge",
  "Eagle Scout|4|merit badge",
  "Bugbear|3|skin",
  "Bugboar|3|tusk",
  "Boogie|3|slime",
  "Camel|2|hump",
  "Carrion Crawler|3|egg",
  "Catoblepas|6|neck",
  "Centaur|4|rib",
  "Centipede|0|leg",
  "Cockatrice|5|wattle",
  "Couatl|9|wing",
  "Crayfish|0|antenna",
  "Demogorgon|53|tentacle",
  "Jubilex|17|gel",
  "Manes|1|tooth",
  "Orcus|27|wand",
  "Succubus|6|bra",
  "Vrock|8|neck",
  "Hezrou|9|leg",
  "Glabrezu|10|collar",
  "Nalfeshnee|11|tusk",
  "Marilith|7|arm",
  "Balor|8|whip",
  "Yeenoghu|25|flail",
  "Asmodeus|52|leathers",
  "Baalzebul|43|pants",
  "Barbed Devil|8|flame",
  "Bone Devil|9|hook",
  "Dispater|30|matches",
  "Erinyes|6|thong",
  "Geryon|30|cornucopia",
  "Malebranche|5|fork",
  "Ice Devil|11|snow",
  "Lemure|3|blob",
  "Pit Fiend|13|seed",
  "Ankylosaurus|9|tail",
  "Brontosaurus|30|brain",
  "Diplodocus|24|fin",
  "Elasmosaurus|15|neck",
  "Gorgosaurus|13|arm",
  "Iguanadon|6|thumb",
  "Megalosaurus|12|jaw",
  "Monoclonius|8|horn",
  "Pentasaurus|12|head",
  "Stegosaurus|18|plate",
  "Triceratops|16|horn",
  "Tyrannosaurus Rex|18|forearm",
  "Djinn|7|lamp",
  "Doppelganger|4|face",
  "Black Dragon|7|*",
  "Plaid Dragon|7|sporrin",
  "Blue Dragon|9|*",
  "Beige Dragon|9|*",
  "Brass Dragon|7|pole",
  "Tin Dragon|8|*",
  "Bronze Dragon|9|medal",
  "Chromatic Dragon|16|scale",
  "Copper Dragon|8|loafer",
  "Gold Dragon|8|filling",
  "Green Dragon|8|*",
  "Platinum Dragon|21|*",
  "Red Dragon|10|cocktail",
  "Silver Dragon|10|*",
  "White Dragon|6|tooth",
  "Dragon Turtle|13|shell",
  "Dryad|2|acorn",
  "Dwarf|1|drawers",
  "Eel|2|sashimi",
  "Efreet|10|cinder",
  "Sand Elemental|8|glass",
  "Bacon Elemental|10|bit",
  "Porn Elemental|12|lube",
  "Cheese Elemental|14|curd",
  "Hair Elemental|16|follicle",
  "Swamp Elf|1|lilypad",
  "Brown Elf|1|tusk",
  "Sea Elf|1|jerkin",
  "Ettin|10|fur",
  "Frog|0|leg",
  "Violet Fungi|3|spore",
  "Gargoyle|4|gravel",
  "Gelatinous Cube|4|jam",
  "Ghast|4|vomit",
  "Ghost|10|*",
  "Ghoul|2|muscle",
  "Humidity Giant|12|drops",
  "Beef Giant|11|steak",
  "Quartz Giant|10|crystal",
  "Porcelain Giant|9|fixture",
  "Rice Giant|8|grain",
  "Cloud Giant|12|condensation",
  "Fire Giant|11|cigarettes",
  "Frost Giant|10|snowman",
  "Hill Giant|8|corpse",
  "Stone Giant|9|hatchling",
  "Storm Giant|15|barometer",
  "Mini Giant|4|pompadour",
  "Gnoll|2|collar",
  "Gnome|1|hat",
  "Goblin|1|ear",
  "Grid Bug|1|carapace",
  "Jellyrock|9|seedling",
  "Beer Golem|15|foam",
  "Oxygen Golem|17|platelet",
  "Cardboard Golem|14|recycling",
  "Rubber Golem|16|ball",
  "Leather Golem|15|fob",
  "Gorgon|8|testicle",
  "Gray Ooze|3|gravy",
  "Green Slime|2|sample",
  "Griffon|7|nest",
  "Banshee|7|larynx",
  "Harpy|3|mascara",
  "Hell Hound|5|tongue",
  "Hippocampus|4|mane",
  "Hippogriff|3|egg",
  "Hobgoblin|1|patella",
  "Homunculus|2|fluid",
  "Hydra|8|gyrum",
  "Imp|2|tail",
  "Invisible Stalker|8|*",
  "Iron Peasant|3|chaff",
  "Jumpskin|3|shin",
  "Kobold|1|penis",
  "Leprechaun|1|wallet",
  "Leucrotta|6|hoof",
  "Lich|11|crown",
  "Lizard Man|2|tail",
  "Lurker|10|sac",
  "Manticore|6|spike",
  "Mastodon|12|tusk",
  "Medusa|6|eye",
  "Multicell|2|dendrite",
  "Pirate|1|booty",
  "Berserker|1|shirt",
  "Caveman|2|club",
  "Dervish|1|robe",
  "Merman|1|trident",
  "Mermaid|1|gills",
  "Mimic|9|hinge",
  "Mind Flayer|8|tentacle",
  "Minotaur|6|map",
  "Yellow Mold|1|spore",
  "Morkoth|7|teeth",
  "Mummy|6|gauze",
  "Naga|9|rattle",
  "Nebbish|1|belly",
  "Neo-Otyugh|11|organ ",
  "Nixie|1|webbing",
  "Nymph|3|hanky",
  "Ochre Jelly|6|nucleus",
  "Octopus|2|beak",
  "Ogre|4|talon",
  "Ogre Mage|5|apparel",
  "Orc|1|snout",
  "Otyugh|7|organ",
  "Owlbear|5|feather",
  "Pegasus|4|aileron",
  "Peryton|4|antler",
  "Piercer|3|tip",
  "Pixie|1|dust",
  "Man-o-war|3|tentacle",
  "Purple Worm|15|dung",
  "Quasit|3|tail",
  "Rakshasa|7|pajamas",
  "Rat|0|tail",
  "Remorhaz|11|protrusion",
  "Roc|18|wing",
  "Roper|11|twine",
  "Rot Grub|1|eggsac",
  "Rust Monster|5|shavings",
  "Satyr|5|hoof",
  "Sea Hag|3|wart",
  "Silkie|3|fur",
  "Shadow|3|silhouette",
  "Shambling Mound|10|mulch",
  "Shedu|9|hoof",
  "Shrieker|3|stalk",
  "Skeleton|1|clavicle",
  "Spectre|7|vestige",
  "Sphinx|10|paw",
  "Spider|0|web",
  "Sprite|1|can",
  "Stirge|1|proboscis",
  "Stun Bear|5|tooth",
  "Stun Worm|2|trode",
  "Su-monster|5|tail",
  "Sylph|3|thigh",
  "Titan|20|sandal",
  "Trapper|12|shag",
  "Treant|10|acorn",
  "Triton|3|scale",
  "Troglodyte|2|tail",
  "Troll|6|hide",
  "Umber Hulk|8|claw",
  "Unicorn|4|blood",
  "Vampire|8|pancreas",
  "Wight|4|lung",
  "Will-o'-the-Wisp|9|wisp",
  "Wraith|5|finger",
  "Wyvern|7|wing",
  "Xorn|7|jaw",
  "Yeti|4|fur",
  "Zombie|2|forehead",
  "Wasp|0|stinger",
  "Rat|1|tail",
  "Bunny|0|ear",
  "Moth|0|dust",
  "Beagle|0|collar",
  "Midge|0|corpse",
  "Ostrich|1|beak",
  "Billy Goat|1|beard",
  "Bat|1|wing",
  "Koala|2|heart",
  "Wolf|2|paw",
  "Whippet|2|collar",
  "Uruk|2|boot",
  "Poroid|4|node",
  "Moakum|8|frenum",
  "Fly|0|*",
  "Hogbird|3|curl",
  "Wolog|4|lemma",
];

K.MonMods = [
  "-4 fœtal *",
  "-4 dying *",
  "-3 crippled *",
  "-3 baby *",
  "-2 adolescent *",
  "-2 very sick *",
  "-1 lesser *",
  "-1 undernourished *",
  "+1 greater *",
  "+1 * Elder",
  "+2 war *",
  "+2 Battle-*",
  "+3 Were-*",
  "+3 undead *",
  "+4 giant *",
  "+4 * Rex",
];

K.OffenseBad = [
  "Dull|-2",
  "Tarnished|-1",
  "Rusty|-3",
  "Padded|-5",
  "Bent|-4",
  "Mini|-4",
  "Rubber|-6",
  "Nerf|-7",
  "Unbalanced|-2",
];

K.DefenseBad = [
  "Holey|-1",
  "Patched|-1",
  "Threadbare|-2",
  "Faded|-1",
  "Rusty|-3",
  "Motheaten|-3",
  "Mildewed|-2",
  "Torn|-3",
  "Dented|-3",
  "Cursed|-5",
  "Plastic|-4",
  "Cracked|-4",
  "Warped|-3",
  "Corroded|-3",
];

K.Races = [
  "Pigman|HP Max",
  "Ashkenazi Jew|CHA",
  "Sweaty Human In A Fursuit|DEX",
  "Apache Helicopter|STR,DEX",
  "Half-Turtle|HP Max,CON",
  "Talking Catfish|CON",
  "Autistic Girl With Elf Ears|WIS",
  "Gray Alien|TP Max,INT",
  "Cat Girl|DEX",
  "Snow Mexican|CON",
  "Giant Dwarf|STR,CON",
  "Trans-Jason|STR,CON",
  "Bird Man|CON,DEX",
  "Three Kids In A Trenchcoat|WIS",
  "Tech Goblin|TP Max",
  "Uncle|WIS",
  "Star Child|DEX,INT",
  "Jeff Bezos Sex Bot|STR",
  "Big Foot|STR,HP Max",
  "Rogue Artificial Intelligence|INT,TP Max",
  "Mothman|DEX,WIS",
  "Ordinary Human|CHA",
];

K.Klasses = [
  "Life Insurance Salesman|WIS,CON",
  "E-Girl|INT,CHA",
  "Cyber Monk|STR,TP Max",
  "Fart Monk|DEX",
  "Political Mage|INT,TP Max",
  "Single Mother|DEX",
  "NASCAR Pit Stop Rear Tire Changer|CON",
  "Sexual Predator Decoy|CHA",
  "Dog Sitter|DEX",
  "Discord Mod|WIS",
  "Cyber Punk|DEX,INT",
  "Felon Drywaller|STR",
  "Police Impersonator|STR,CON",
  "Eco Terrorist|CON",
  "Father Figure|CON",
  "HOA President|WIS",
  "Pro Hoverboarder|DEX",
  "Hacker|INT,TP Max",
  "Civil War Reenactor|CON",
];

K.Titles = [
  "Mr.",
  "Mrs.",
  "Sir",
  "Sgt.",
  "Ms.",
  "Captain",
  "Chief",
  "Admiral",
  "Saint",
  "CEO",
];

K.ImpressiveTitles = [
  "King",
  "Queen",
  "Techlord",
  "Lady",
  "Viceroy",
  "Mayor",
  "Prince",
  "Princess",
  "Chief",
  "Boss",
  "Lord",
  "Techlady",
  "President",
  "Dictator",
  "Pope",
];
