let RevString = "&rev=6";
// Rev strings known to server, probably:
// rev=3 is the minimum allowed by server, probably pq6.1
// rev=4 is pq6.2 the longstanding delphi client
// rev=5 is pq6.3 presumably the lazarus port or other unofficial release
// rev=6 is this here, pq-web multiplayer enabled

var K = {};

K.Traits = ["Name", "Race", "Class", "Level"];

K.PrimeStats = ["STR", "CON", "DEX", "INT", "WIS", "CHA"];
K.Stats = K.PrimeStats.slice(0).concat(["HP Max", "TP Max"]);

K.Equips = [
  "Weapon",
  "Accessory",
  "Headwear",
  "Eyewear",
  "Body Armor",
  "Jacket",
  "Gloves",
  "Wristwear",
  "Belt",
  "Legwear",
  "Footwear",
];

K.Spells = [
  "Basic Cooking",
  "Time Management",
  "Public Speaking",
  "First Aid",
  "Personal Finance",
  "Social Media",
  "Computer Basics",
  "Foreign Language",
  "Project Management",
  "Data Analysis",
  "Digital Marketing",
  "Programming",
  "Cybersecurity",
  "AI Interaction",
  "Virtual Reality",
  "Drone Operation",
  "Cryptocurrency Trading",
  "Neural Interface",
  "Quantum Computing",
  "Reality Hacking",
  "Consciousness Transfer",
  "Biometric Manipulation",
  "Temporal Navigation",
  "Memory Implantation",
  "Synthetic Telepathy",
  "Digital Immortality",
  "Neural Network Integration",
  "Quantum Entanglement Control",
  "Reality Matrix Access",
  "Omniscient Data Mining",
];

K.OffenseAttrib = [
  "Polished|+1",
  "Serrated|+1",
  "Heavy|+1",
  "Pronged|+2",
  "Steely|+2",
  "Vicious|+3",
  "Venomed|+4",
  "Stabbity|+4",
  "Dancing|+5",
  "Invisible|+6",
  "Vorpal|+7",
];

K.DefenseAttrib = [
  "Studded|+1",
  "Banded|+2",
  "Gilded|+2",
  "Festooned|+3",
  "Holy|+4",
  "Cambric|+1",
  "Fine|+4",
  "Impressive|+5",
  "Custom|+3",
];

K.Accessories = [
  "Safety Pin|0",
  "Dog Tags|1",
  "Cigarette Lighter|2",
  "Key Chain|3",
  "Wallet|4",
  "Business Card|4",
  "USB Drive|5",
  "Compass|5",
  "Multi-tool|6",
  "Flash Drive|6",
  "Credit Card Scanner|7",
  "RFID Badge|8",
  "Crypto Wallet|9",
  "Holographic Badge|11",
  "Neural Implant Chip|12",
  "Quantum Communicator|15",
  "Bio-Scanner Pendant|16",
  "Synthetic Memory Core|17",
  "Dimensional Anchor|18",
  "Reality Distortion Field|20",
];

K.Headwear = [
  "Baseball Cap|0",
  "Beanie|1",
  "Hard Hat|2",
  "Beret|3",
  "Motorcycle Helmet|4",
  "Sports Helmet|4",
  "Tactical Helmet|5",
  "Combat Helmet|5",
  "Riot Helmet|6",
  "Flight Helmet|6",
  "Smart Helmet|7",
  "HUD Helmet|8",
  "Neural Helmet|9",
  "Cyber Crown|11",
  "Mind Shield|12",
  "Quantum Headset|15",
  "Neural Interface Crown|16",
  "Thought Amplifier|17",
  "Consciousness Projector|18",
  "Reality Perception Filter|20",
];

K.Eyewear = [
  "Reading Glasses|0",
  "Sunglasses|1",
  "Safety Glasses|2",
  "Prescription Glasses|3",
  "Ski Goggles|4",
  "Swimming Goggles|4",
  "Tactical Goggles|5",
  "Night Vision Goggles|5",
  "Welding Mask|6",
  "VR Headset|6",
  "Smart Glasses|7",
  "AR Visor|8",
  "Targeting Monocle|9",
  "Cyber Eyes|11",
  "Neural Optics|12",
  "Quantum Vision|15",
  "Reality Scanner|16",
  "Dimensional Viewer|17",
  "Temporal Sight|18",
  "Omniscient Lens|20",
];

K.BodyArmor = [
  "T-Shirt|0",
  "Thick Shirt|1",
  "Padded Vest|2",
  "Leather Jacket|3",
  "Stab Vest|4",
  "Security Vest|4",
  "Bulletproof Vest|5",
  "Tactical Vest|5",
  "Body Armor|6",
  "Military Vest|6",
  "Riot Armor|7",
  "Combat Armor|8",
  "Power Armor|9",
  "Nano Armor|11",
  "Energy Shield|12",
  "Plasma Barrier|15",
  "Quantum Armor|16",
  "Reality Plating|17",
  "Void Protection|18",
  "Invulnerability Field|20",
];

K.Jackets = [
  "Windbreaker|0",
  "Hoodie|1",
  "Jean Jacket|2",
  "Bomber Jacket|3",
  "Leather Jacket|4",
  "Trench Coat|4",
  "Military Jacket|5",
  "Tactical Jacket|5",
  "Kevlar Coat|6",
  "Armored Jacket|6",
  "Smart Jacket|7",
  "Climate Suit|8",
  "Power Coat|9",
  "Nano Jacket|11",
  "Energy Cloak|12",
  "Stealth Coat|15",
  "Phase Jacket|16",
  "Quantum Cloak|17",
  "Dimensional Wrap|18",
  "Reality Shroud|20",
];

K.Gloves = [
  "Work Gloves|0",
  "Rubber Gloves|1",
  "Winter Gloves|2",
  "Driving Gloves|3",
  "Leather Gloves|4",
  "Ski Gloves|4",
  "Tactical Gloves|5",
  "Combat Gloves|5",
  "Kevlar Gloves|6",
  "Armored Gloves|6",
  "Smart Gloves|7",
  "Grip Enhancers|8",
  "Power Gloves|9",
  "Cyber Gauntlets|11",
  "Neural Gloves|12",
  "Quantum Mitts|15",
  "Phase Gloves|16",
  "Reality Manipulators|17",
  "Void Handlers|18",
  "Omnipotent Grasp|20",
];

K.Wristwear = [
  "Cloth Band|0",
  "Rubber Band|1",
  "Leather Band|2",
  "Digital Watch|3",
  "Sports Watch|4",
  "Smart Watch|4",
  "Fitness Tracker|5",
  "Tactical Watch|5",
  "Computer Watch|6",
  "Comm Device|6",
  "Bio Monitor|7",
  "Neural Link|8",
  "Quantum Timer|9",
  "Cyber Interface|11",
  "Mind Bridge|12",
  "Temporal Controller|15",
  "Reality Sync|16",
  "Dimensional Anchor|17",
  "Time Manipulator|18",
  "Infinity Band|20",
];

K.Belts = [
  "Rope Belt|0",
  "Cloth Belt|1",
  "Leather Belt|2",
  "Canvas Belt|3",
  "Utility Belt|4",
  "Tool Belt|4",
  "Tactical Belt|5",
  "Military Belt|5",
  "Equipment Belt|6",
  "Combat Belt|6",
  "Smart Belt|7",
  "Tech Belt|8",
  "Power Belt|9",
  "Cyber Belt|11",
  "Neural Belt|12",
  "Quantum Belt|15",
  "Phase Belt|16",
  "Reality Belt|17",
  "Dimensional Belt|18",
  "Omnipotent Sash|20",
];

K.Legwear = [
  "Jeans|0",
  "Sweatpants|1",
  "Cargo Pants|2",
  "Khakis|3",
  "Tactical Pants|4",
  "Military Pants|4",
  "Combat Pants|5",
  "Armored Pants|5",
  "Kevlar Pants|6",
  "Riot Pants|6",
  "Smart Pants|7",
  "Tech Leggings|8",
  "Power Pants|9",
  "Cyber Legs|11",
  "Neural Pants|12",
  "Quantum Legwear|15",
  "Phase Pants|16",
  "Reality Legs|17",
  "Dimensional Pants|18",
  "Void Leggings|20",
];

K.Footwear = [
  "Sneakers|0",
  "Sandals|1",
  "Work Boots|2",
  "Hiking Boots|3",
  "Combat Boots|4",
  "Steel Toes|4",
  "Tactical Boots|5",
  "Military Boots|5",
  "Armored Boots|6",
  "Jump Boots|6",
  "Smart Shoes|7",
  "Hover Boots|8",
  "Power Boots|9",
  "Cyber Feet|11",
  "Neural Soles|12",
  "Quantum Boots|15",
  "Phase Walkers|16",
  "Reality Steppers|17",
  "Dimensional Boots|18",
  "Omnipresent Shoes|20",
];

K.Armors = [
  "Lace|1",
  "Macrame|2",
  "Burlap|3",
  "Canvas|4",
  "Flannel|5",
  "Chamois|6",
  "Pleathers|7",
  "Leathers|8",
  "Bearskin|9",
  "Ringmail|10",
  "Scale Mail|12",
  "Chainmail|14",
  "Splint Mail|15",
  "Platemail|16",
  "ABS|17",
  "Kevlar|18",
  "Titanium|19",
  "Mithril Mail|20",
  "Diamond Mail|25",
  "Plasma|30",
];

K.Weapons = [
  "Pool Noodle|0",
  "Rotten Banana Peel|0",
  "Rubber Chicken|0",
  "Foam Finger|0",
  "Balloon Sword|0",
  "Fly Swatter|0",
  "Windshield Wiper|0",
  "Rubber Band|0",
  "Oven Mitt|0",
  "Bubble Wand|0",
  "Foam LARPing Sword|1",
  "Dust Pan|1",
  "Cool Stick|1",
  "Stale Baguette|1",
  "Plastic Spork|1",
  "Toilet Plunger|1",
  "Pool Cue|2",
  "Baseball Bat|2",
  "Golf Club|2",
  "Tire Iron|3",
  "Ice Pick|4",
  "Nail Gun|4",
  "Ball-peen Hammer|3",
  "Chainsaw|4",
  "Razor Blade|4",
  "Weed Whacker|3",
  "Flare Gun|5",
  "Tranquilizer|5",
  "Potato Cannon|5",
  "Crossbow|5",
  "Compound Bow|5",
  "9mm Pistol|6",
  ".38 Special|6",
  "Glock 17|6",
  "Makarov|6",
  ".45 ACP|7",
  "Desert Eagle|7",
  "AK-47|7",
  "SPAS-12|7",
  "SKS|7",
  "Barrett M82|8",
  "AWP|8",
  "M79 Grenade Launcher|9",
  "Rail Gun Prototype|9",
  "RPG-7|10",
  "Bazooka|10",
  "Spatula|1",
  "Encyclopedia|1",
  "Umbrella|1",
  "Dodgeball|1",
  "Butter Knife|2",
  "Rolling Pin|2",
  "Stapler|2",
  "Metal Fork|2",
  "Christmas Ornaments in a Sock|2",
  "Walking Stick|2",
  "Bowling Ball|2",
  "Staple Gun|3",
  "Pitchfork|3",
  "Weed Whacker|3",
  "Crowbar|4",
  "Blowtorch|3",
  "Sledgehammer|3",
  "Pencil|3",
  "Croquet Mallot|3",
  "Nunchucks|4",
  "Brass Knuckles|4",
  "Taser|4",
  "Switchblade|4",
  "Bowie Knife|4",
  ".22 Pistol|5",
  "Derringer|5",
  ".22 Rifle|5",
  "Medieval Trebuchet|5",
  "BB Gun|5",
  "H&K USP|6",
  "Beretta 92|6",
  "Bolt Action Rifle|6",
  "Snubnose Revolver|6",
  ".30-06 Rifle|6",
  "Mossberg 500|6",
  "Mini-14|7",
  "MAC-10|7",
  "Tommy Gun|7",
  "FN FAL|7",
  "Grease Gun|7",
  "SR-25|8",
  "Anti-Material Rifle|8",
  "SCAR-H|8",
  "AA-12|8",
  "M249|8",
  "PKP|8",
  "Steyr Scout|8",
  "Negev|8",
  "BAR|9",
  "McMillan TAC-50|9",
  "PKM|9",
  "Harpoon Gun|9",
  "Pirate Ship Cannon|9",
  "XM25|9",
  "RPK|9",
  "M60|9",
  "M224 Mortar|10",
  "M242 Bushmaster|10",
  "M134 Minigun|10",
];

K.Specials = [
  "Diadem",
  "Festoon",
  "Gemstone",
  "Phial",
  "Tiara",
  "Scabbard",
  "Arrow",
  "Lens",
  "Lamp",
  "Hymnal",
  "Fleece",
  "Laurel",
  "Brooch",
  "Gimlet",
  "Cobble",
  "Albatross",
  "Brazier",
  "Bandolier",
  "Tome",
  "Garnet",
  "Amethyst",
  "Candelabra",
  "Corset",
  "Sphere",
  "Sceptre",
  "Ankh",
  "Talisman",
  "Orb",
  "Gammel",
  "Ornament",
  "Brocade",
  "Galoon",
  "Bijou",
  "Spangle",
  "Gimcrack",
  "Hood",
  "Vulpeculum",
];

K.ItemAttrib = [
  "Golden",
  "Gilded",
  "Spectral",
  "Astral",
  "Garlanded",
  "Precious",
  "Crafted",
  "Dual",
  "Filigreed",
  "Cruciate",
  "Arcane",
  "Blessed",
  "Reverential",
  "Lucky",
  "Enchanted",
  "Gleaming",
  "Grandiose",
  "Sacred",
  "Legendary",
  "Mythic",
  "Crystalline",
  "Austere",
  "Ostentatious",
  "One True",
  "Proverbial",
  "Fearsome",
  "Deadly",
  "Benevolent",
  "Unearthly",
  "Magnificent",
  "Iron",
  "Ormolu",
  "Puissant",
];

K.ItemOfs = [
  "Foreboding",
  "Foreshadowing",
  "Nervousness",
  "Happiness",
  "Torpor",
  "Danger",
  "Craft",
  "Silence",
  "Invisibility",
  "Rapidity",
  "Pleasure",
  "Practicality",
  "Hurting",
  "Joy",
  "Petulance",
  "Intrusion",
  "Chaos",
  "Suffering",
  "Extroversion",
  "Frenzy",
  "Sisu",
  "Solitude",
  "Punctuality",
  "Efficiency",
  "Comfort",
  "Patience",
  "Internment",
  "Incarceration",
  "Misapprehension",
  "Loyalty",
  "Envy",
  "Acrimony",
  "Worry",
  "Fear",
  "Awe",
  "Guile",
  "Prurience",
  "Fortune",
  "Perspicacity",
  "Domination",
  "Submission",
  "Fealty",
  "Hunger",
  "Despair",
  "Cruelty",
  "Grob",
  "Dignard",
  "Ra",
  "the Bone",
  "Diamonique",
  "Electrum",
  "Hydragyrum",
];

K.BoringItems = [
  "nail",
  "lunchpail",
  "sock",
  "I.O.U.",
  "cookie",
  "pint",
  "toothpick",
  "writ",
  "newspaper",
  "letter",
  "plank",
  "hat",
  "egg",
  "coin",
  "needle",
  "bucket",
  "ladder",
  "chicken",
  "twig",
  "dirtclod",
  "counterpane",
  "vest",
  "teratoma",
  "bunny",
  "rock",
  "pole",
  "carrot",
  "canoe",
  "inkwell",
  "hoe",
  "bandage",
  "trowel",
  "towel",
  "planter box",
  "anvil",
  "axle",
  "tuppence",
  "casket",
  "nosegay",
  "trinket",
  "credenza",
  "writ",
];

K.Monsters = [
  "Anhkheg|6|chitin",
  "Ant|0|antenna",
  "Ape|4|ass",
  "Baluchitherium|14|ear",
  "Beholder|10|eyestalk",
  "Black Pudding|10|saliva",
  "Blink Dog|4|eyelid",
  "Cub Scout|1|neckerchief",
  "Girl Scout|2|cookie",
  "Boy Scout|3|merit badge",
  "Eagle Scout|4|merit badge",
  "Bugbear|3|skin",
  "Bugboar|3|tusk",
  "Boogie|3|slime",
  "Camel|2|hump",
  "Carrion Crawler|3|egg",
  "Catoblepas|6|neck",
  "Centaur|4|rib",
  "Centipede|0|leg",
  "Cockatrice|5|wattle",
  "Couatl|9|wing",
  "Crayfish|0|antenna",
  "Demogorgon|53|tentacle",
  "Jubilex|17|gel",
  "Manes|1|tooth",
  "Orcus|27|wand",
  "Succubus|6|bra",
  "Vrock|8|neck",
  "Hezrou|9|leg",
  "Glabrezu|10|collar",
  "Nalfeshnee|11|tusk",
  "Marilith|7|arm",
  "Balor|8|whip",
  "Yeenoghu|25|flail",
  "Asmodeus|52|leathers",
  "Baalzebul|43|pants",
  "Barbed Devil|8|flame",
  "Bone Devil|9|hook",
  "Dispater|30|matches",
  "Erinyes|6|thong",
  "Geryon|30|cornucopia",
  "Malebranche|5|fork",
  "Ice Devil|11|snow",
  "Lemure|3|blob",
  "Pit Fiend|13|seed",
  "Ankylosaurus|9|tail",
  "Brontosaurus|30|brain",
  "Diplodocus|24|fin",
  "Elasmosaurus|15|neck",
  "Gorgosaurus|13|arm",
  "Iguanadon|6|thumb",
  "Megalosaurus|12|jaw",
  "Monoclonius|8|horn",
  "Pentasaurus|12|head",
  "Stegosaurus|18|plate",
  "Triceratops|16|horn",
  "Tyrannosaurus Rex|18|forearm",
  "Djinn|7|lamp",
  "Doppelganger|4|face",
  "Black Dragon|7|*",
  "Plaid Dragon|7|sporrin",
  "Blue Dragon|9|*",
  "Beige Dragon|9|*",
  "Brass Dragon|7|pole",
  "Tin Dragon|8|*",
  "Bronze Dragon|9|medal",
  "Chromatic Dragon|16|scale",
  "Copper Dragon|8|loafer",
  "Gold Dragon|8|filling",
  "Green Dragon|8|*",
  "Platinum Dragon|21|*",
  "Red Dragon|10|cocktail",
  "Silver Dragon|10|*",
  "White Dragon|6|tooth",
  "Dragon Turtle|13|shell",
  "Dryad|2|acorn",
  "Dwarf|1|drawers",
  "Eel|2|sashimi",
  "Efreet|10|cinder",
  "Sand Elemental|8|glass",
  "Bacon Elemental|10|bit",
  "Porn Elemental|12|lube",
  "Cheese Elemental|14|curd",
  "Hair Elemental|16|follicle",
  "Swamp Elf|1|lilypad",
  "Brown Elf|1|tusk",
  "Sea Elf|1|jerkin",
  "Ettin|10|fur",
  "Frog|0|leg",
  "Violet Fungi|3|spore",
  "Gargoyle|4|gravel",
  "Gelatinous Cube|4|jam",
  "Ghast|4|vomit",
  "Ghost|10|*",
  "Ghoul|2|muscle",
  "Humidity Giant|12|drops",
  "Beef Giant|11|steak",
  "Quartz Giant|10|crystal",
  "Porcelain Giant|9|fixture",
  "Rice Giant|8|grain",
  "Cloud Giant|12|condensation",
  "Fire Giant|11|cigarettes",
  "Frost Giant|10|snowman",
  "Hill Giant|8|corpse",
  "Stone Giant|9|hatchling",
  "Storm Giant|15|barometer",
  "Mini Giant|4|pompadour",
  "Gnoll|2|collar",
  "Gnome|1|hat",
  "Goblin|1|ear",
  "Grid Bug|1|carapace",
  "Jellyrock|9|seedling",
  "Beer Golem|15|foam",
  "Oxygen Golem|17|platelet",
  "Cardboard Golem|14|recycling",
  "Rubber Golem|16|ball",
  "Leather Golem|15|fob",
  "Gorgon|8|testicle",
  "Gray Ooze|3|gravy",
  "Green Slime|2|sample",
  "Griffon|7|nest",
  "Banshee|7|larynx",
  "Harpy|3|mascara",
  "Hell Hound|5|tongue",
  "Hippocampus|4|mane",
  "Hippogriff|3|egg",
  "Hobgoblin|1|patella",
  "Homunculus|2|fluid",
  "Hydra|8|gyrum",
  "Imp|2|tail",
  "Invisible Stalker|8|*",
  "Iron Peasant|3|chaff",
  "Jumpskin|3|shin",
  "Kobold|1|penis",
  "Leprechaun|1|wallet",
  "Leucrotta|6|hoof",
  "Lich|11|crown",
  "Lizard Man|2|tail",
  "Lurker|10|sac",
  "Manticore|6|spike",
  "Mastodon|12|tusk",
  "Medusa|6|eye",
  "Multicell|2|dendrite",
  "Pirate|1|booty",
  "Berserker|1|shirt",
  "Caveman|2|club",
  "Dervish|1|robe",
  "Merman|1|trident",
  "Mermaid|1|gills",
  "Mimic|9|hinge",
  "Mind Flayer|8|tentacle",
  "Minotaur|6|map",
  "Yellow Mold|1|spore",
  "Morkoth|7|teeth",
  "Mummy|6|gauze",
  "Naga|9|rattle",
  "Nebbish|1|belly",
  "Neo-Otyugh|11|organ ",
  "Nixie|1|webbing",
  "Nymph|3|hanky",
  "Ochre Jelly|6|nucleus",
  "Octopus|2|beak",
  "Ogre|4|talon",
  "Ogre Mage|5|apparel",
  "Orc|1|snout",
  "Otyugh|7|organ",
  "Owlbear|5|feather",
  "Pegasus|4|aileron",
  "Peryton|4|antler",
  "Piercer|3|tip",
  "Pixie|1|dust",
  "Man-o-war|3|tentacle",
  "Purple Worm|15|dung",
  "Quasit|3|tail",
  "Rakshasa|7|pajamas",
  "Rat|0|tail",
  "Remorhaz|11|protrusion",
  "Roc|18|wing",
  "Roper|11|twine",
  "Rot Grub|1|eggsac",
  "Rust Monster|5|shavings",
  "Satyr|5|hoof",
  "Sea Hag|3|wart",
  "Silkie|3|fur",
  "Shadow|3|silhouette",
  "Shambling Mound|10|mulch",
  "Shedu|9|hoof",
  "Shrieker|3|stalk",
  "Skeleton|1|clavicle",
  "Spectre|7|vestige",
  "Sphinx|10|paw",
  "Spider|0|web",
  "Sprite|1|can",
  "Stirge|1|proboscis",
  "Stun Bear|5|tooth",
  "Stun Worm|2|trode",
  "Su-monster|5|tail",
  "Sylph|3|thigh",
  "Titan|20|sandal",
  "Trapper|12|shag",
  "Treant|10|acorn",
  "Triton|3|scale",
  "Troglodyte|2|tail",
  "Troll|6|hide",
  "Umber Hulk|8|claw",
  "Unicorn|4|blood",
  "Vampire|8|pancreas",
  "Wight|4|lung",
  "Will-o'-the-Wisp|9|wisp",
  "Wraith|5|finger",
  "Wyvern|7|wing",
  "Xorn|7|jaw",
  "Yeti|4|fur",
  "Zombie|2|forehead",
  "Wasp|0|stinger",
  "Rat|1|tail",
  "Bunny|0|ear",
  "Moth|0|dust",
  "Beagle|0|collar",
  "Midge|0|corpse",
  "Ostrich|1|beak",
  "Billy Goat|1|beard",
  "Bat|1|wing",
  "Koala|2|heart",
  "Wolf|2|paw",
  "Whippet|2|collar",
  "Uruk|2|boot",
  "Poroid|4|node",
  "Moakum|8|frenum",
  "Fly|0|*",
  "Hogbird|3|curl",
  "Wolog|4|lemma",
];

K.MonMods = [
  "-4 fœtal *",
  "-4 dying *",
  "-3 crippled *",
  "-3 baby *",
  "-2 adolescent *",
  "-2 very sick *",
  "-1 lesser *",
  "-1 undernourished *",
  "+1 greater *",
  "+1 * Elder",
  "+2 war *",
  "+2 Battle-*",
  "+3 Were-*",
  "+3 undead *",
  "+4 giant *",
  "+4 * Rex",
];

K.OffenseBad = [
  "Dull|-2",
  "Tarnished|-1",
  "Rusty|-3",
  "Padded|-5",
  "Bent|-4",
  "Mini|-4",
  "Rubber|-6",
  "Nerf|-7",
  "Unbalanced|-2",
];

K.DefenseBad = [
  "Holey|-1",
  "Patched|-1",
  "Threadbare|-2",
  "Faded|-1",
  "Rusty|-3",
  "Motheaten|-3",
  "Mildewed|-2",
  "Torn|-3",
  "Dented|-3",
  "Cursed|-5",
  "Plastic|-4",
  "Cracked|-4",
  "Warped|-3",
  "Corroded|-3",
];

K.Races = [
  "Pigman|HP Max",
  "Ashkenazi Jew|CHA",
  "Sweaty Human In A Fursuit|DEX",
  "Apache Helicopter|STR,DEX",
  "Half-Turtle|HP Max,CON",
  "Talking Catfish|CON",
  "Autistic Girl With Elf Ears|WIS",
  "Gray Alien|TP Max,INT",
  "Cat Girl|DEX",
  "Snow Mexican|CON",
  "Giant Dwarf|STR,CON",
  "Trans-Jason|STR,CON",
  "Bird Man|CON,DEX",
  "Three Kids In A Trenchcoat|WIS",
  "Tech Goblin|TP Max",
  "Uncle|WIS",
  "Star Child|DEX,INT",
  "Jeff Bezos Sex Bot|STR",
  "Big Foot|STR,HP Max",
  "Rogue Artificial Intelligence|INT,TP Max",
  "Mothman|DEX,WIS",
  "Ordinary Human|CHA",
];

K.Klasses = [
  "Life Insurance Salesman|WIS,CON",
  "E-Girl|INT,CHA",
  "Cyber Monk|STR,TP Max",
  "Fart Monk|DEX",
  "Political Mage|INT,TP Max",
  "Single Mother|DEX",
  "NASCAR Pit Stop Rear Tire Changer|CON",
  "Sexual Predator Decoy|CHA",
  "Dog Sitter|DEX",
  "Discord Mod|WIS",
  "Cyber Punk|DEX,INT",
  "Felon Drywaller|STR",
  "Police Impersonator|STR,CON",
  "Eco Terrorist|CON",
  "Father Figure|CON",
  "HOA President|WIS",
  "Pro Hoverboarder|DEX",
  "Hacker|INT,TP Max",
  "Civil War Reenactor|CON",
];

K.Titles = [
  "Mr.",
  "Mrs.",
  "Sir",
  "Sgt.",
  "Ms.",
  "Captain",
  "Chief",
  "Admiral",
  "Saint",
  "CEO",
];

K.ImpressiveTitles = [
  "King",
  "Queen",
  "Techlord",
  "Lady",
  "Viceroy",
  "Mayor",
  "Prince",
  "Princess",
  "Chief",
  "Boss",
  "Lord",
  "Techlady",
  "President",
  "Dictator",
  "Pope",
];
